{
  "data": [
  	"This event was labeled in history as the \"birth of aviation\"",
  	"I am determined to be cheerful and happy in whatever situation I may find myself",
  	"An emotion is an intense feeling",
  	"Happiness is one of the many emotions humans experience",
  	"I think I may have \"missed the boat\". I should’ve done it last week",
  	"Technology has changed our lives but, has it made our lives any better?",
  	"Hey, you shouldn’t \"judge a book by its cover\"",
  	"I will \"when pigs fly\"",
  	"A smile, a laugh, a quick thought, starry nights, walking in warm rain storms, playing soccer, chocolate",
  	"He \"bit off more than he could chew\", and I don’t think he can handle it anymore",
  	"It’ll \"cost an arm and a leg\"",
  	"I am such a \"catch\"",
  	"Come on, \"it’s a no-brainer\"",
  	"I must tell him how I feel about him, \"let the chips fall where they may\"",
  	"I feel quite \"under the weather\" today",
  	"Oh, really? \"I couldn’t care less\"",
  	"\"Just hang in there\" and he will call you",
  	"Our local MP \"came out swinging against the current\" leadership and demanded that the government resign",
  	"His career went \"down in flames\" when they found out she’d been leaking information to our competitors",
  	"I’m not \"blowing smoke\". I have honestly read War and Peace by Tolstoy",
  	"she always \"went the extra mile\" for us",
  	"This is the last time I’m telling you to arrive on time. \"Shape up or ship out\"",
  	"I understand you’ve had a bad day, but \"pull yourself together\" and get on with your job",
  	"I wasn’t sure how she was going to react, but I had to \"get it out of my system\"",
  	"I’ll \"leave no stone unturned\" until I find out who did this",
  	"The party \"got out of hand\" and the guests started to throw bottles at each other",
  	"They were surprised at the Christmas party- \"I let my freak flag fly\" and showed them a break dance routine",
  	"They say \"A barking dog never bites\"",
  	"Hugo A. Bedau wrote \"The Death Penalty in America\"",
  	"The V in V-2 rocket stood for \"vengeance weapon\"",
  	"The \"northern barbarians\" savaged and conquered much of Europe in its early history",
  	"Aschenbach is known as the main character in the novel \"Death in Venice\"",
  	"I thought we were going bankrupt, but my partner \"pulled a rabbit out of his hat\"",
  	"If you want to get on well with your boss, try not to \"shoot from the hip\" next time",
  	"I was extremely busy last week. \"Cut me some slack\" and I’ll finish the report by tomorrow morning",
  	"The hopelessness of such a situation is depicted in \"The Death of the Moth\"",
  	"The death penalty does one thing it \"kills\"",
  	"\"The Masque of the Red Death\" is an extraordinary story",
  	"We are here chasing the \"American Dream\"",
  	"Michael Lee Wilson's final words were, \"I feel my whole body burning\"",
  	"Perhaps the Beatles were right that a diamond ring can’t buy (me) love",
  	"The Code of Hammurabi first established the action of retalitation and retribution of \"an eye for an eye\"",
  	"Loss of soul reduces a person to the statues condition of \"corpse\"",
  	"Everybody in this world has the right to happiness",
  	"Who do you think has the best life on the earth",
  	"Over time people have discovered more \"humane\" ways to execute a convicted criminal",
  	"There is no \"global\" standard",
  	"Is life really about money, expensive jewelry, and shiny fast cars?",
  	"So I am a girl",
  	"What do you want to find here",
  	"Their farm was two hundred acres of corn fields, cows, pigs, and, of course, chickens",
  	"Society's punishments are a window through which society's \"true nature\" can be viewed",
  	"The story of In \"The Death of Ivan Ilych\" was written by Leo Tolstoy",
  	"Happiness is a sensation that people want to have, and a lot of it",
  	"Edgar Allan Poe wrote \"The Masque of Red Death\"",
  	"Capital punishment is known as \"The Death Penalty\"",
  	"We are living the \"American Nightmare\"",
  	"\"The Greatest Happiness Principle\" was introduced by Jeremy Bentham",
  	"Wealth could be something tangible, such as money, things, or even a well-deserved promotion",
  	"What does all that lead to",
  	"There are always bumps in the road, but how do we get back on the \"road to happiness?\"",
  	"what philosophers call \"raw feels\": ecstasy, thrills, orgasm, delight, mirth, exuberance, and comfort",
  	"When we are young children, we are introduced to the concept of \"living happily ever after\"",
  	"Happiness is everyone wants to have",
  	"You maybe successful, but without happiness it will be meaningless",
  	"Some people say happiness is only temporary",
  	"Happiness is not something really made, it comes from your action",
  	"Laughter is very crucial in social settings",
  	"More than a word, \"happiness\" is what we really need and always seek in life",
  	"Plato emphasizes that \"human being naturally desires the happiness\"",
  	"I read the eassay \"On Dumpster Diving\"",
  	"Happiness symbolises a form of content",
  	"Happiness is a form of satisfaction that can lead to several types of actions",
  	"Happiness is portrayed in unusual forms with different characters",
  	"The Egg represents the symbol of birth and life",
  	"Paranoid schizophrenia is the reverse of happiness",
  	"Pleasure, elation, and satisfaction are elusive",
  	"It feels like you are the only one to whom this is happening",
  	"I want mountain bike for my birthday",
  	"Our society is attracted to material things, rather than spiritual ones",
  	"She’s such a fantastic woman",
  	"Little was known about the clergy during the Black Death",
  	"Death is a subject many fear",
  	"It's a small phrase when you think about it: \"the pursuit of happiness.\"",
  	"Aristotle and Plato are both well known for their focus on defining the purpose of being human",
  	"Humans have a particular characteristic that no other living thing possesses",
  	"Humans strive to achieve a level of goodness",
  	"What steps can be taken to create internal happiness",
  	"Western society has an obsession. It is a dark and crippling fixation",
  	"A library of wisdom, is more precious than all wealth",
  	"Most folks are as happy as they make up their minds to be",
  	"What is happiness",
  	"Even though Death is all a part of life, it’s really a difficult thing to find in the art world",
  	"Can lust lead to your death bed",
  	"People have many different views about what traveling means to them",
  	"I set out to discover how these views",
  	"Individuals try to find happiness, but like water or air, it is hard to clench in your hands",
  	"Unfortunately tyranny and oppression has many examples in history",
  	"I am interested in how people have differing mindsets when it comes to travel"	 
  ]
}