{
  "data": [
    "Why is it that heartache almost always precede after the act of first love",
    "Things would be simpler if timing were not a crucial factor in romance",
    "Your vision and hopes are suspenseful; you never imagined it like this",
    "But what do you do when you have to face the possibility that it will not go your way this time",
    "Love, you say, is \"a two way thing\"",
    "A small, mechanical \"plip\" interrupted her thoughts",
    "They could have been famous from inventing the \"next great thing\"",
    "Choosing to blame the humans for his mistake, Puck says \"Lord, what fools these mortals be!\"",
    "I started a newsletter called \"Youth In Depth\"",
    "The nurse gave you \"I was brave!\" stickers",
    "Engages in \"lunatic\" thoughts",
    "Sit at the dining room table and create \"princesses\"",
    "Nathanial Emmons once said, \"Insanity destroys reason, but not wit\"",
    "This period, \"An Age of Reason, An Age of Passion,\" had a dual nature—rational",
    "One definition of madness is \"mental delusion or the eccentric behavior arising from it.\"",
    "Where I'm from we like to say \"Surfing is an addiction, a pleasure rush.\"",
    "William's poem  \"Sailing to Byzantium\" had many complex themes",
    "Socrates said in 399 B.C., \"The unexplained life is not worth living\"",
    "Historians and critics often look upon the 18th Century as \"The Age of Reason\"",
    "The real and positive pride, is \"the consciousness of one’s own dignity\"",
    "They say \"Heaven has no rage\"",
    "She \"Hates the Wait\"",
    "Shakespeare maybe tried to prove that \"love at first sight\" does not exist",
    "The word \"propaganda\" however, has a very negative connotation",
    "I love the very term \"sin\"",
    "African American History: \"Heritage, not Hate\"",
    "\"Long Walk to Freedom\" an autobiography by Nelson Mandela",
    "The contrast of love and hate in the play by Shakespeare \"Romeo and Juliet\"",
    "Said \"go nuts\"",
    "\"It’s crunch time\" at work",
    "I just \"can’t get my head around the fact\" that I'm not getting paid for this",
    "I’d been \"pounding the pavement\" for months before I found a job",
    "If you want to win this competition, you’ll have to \"step up your game\"",
    "OK, \"you’ve sold me\", I’ll go to the match with you",
    "The exhibition just \"blew me away\"",
    "Is he just \"crying wolf\"",
    "She was \"tickled pink\" by all the compliments she’d received",
    "Check out our \"baker’s dozen\" language learning tips",
    "It’s so nice to make some \"comfort food\" and settle down with a good book",
    "We’re operating with a \"skeleton crew\" at the moment",
    "Come on, it’s a \"no-brainer\"",
    "I’m going to \"hit the books\". I have an exam coming up soon",
    "Vanessa. \"You rock!\"",
    "A person in love feels stronger, faster, better overall",
    "Love is no telepathy", 
    "Force fields can’t be perfect so if someone brakes through and you became injured love has the power to heal",
    "When we are having fun, time passes swiftly away",
    "Imagine having to choose to reside in one place for the rest of your life",
    "The hyperactive lifestyle that a big city has to offer has more benefits than living in the country",
    "The calm and peaceful environment of the countryside is much more rewarding",
    "People move from the city to a farm to get away from the hustle and bustle",
     "\"Is it time to go home yet?\" is the most common phrase heard around the Marine Corps on weekdays",
    "Throughout the book \"My Antonia\" by Willa Cather, there is a twisting and turning of Sexual and Gender issues",
    "The man \"had ceased to wonder in her long black hair\"",
    "It's hard to find an \"in-between.\"",
    "\"What happens in Vegas stays in Vegas\"",
    "Farmers have traded in their tractors and animals to live a fast paced city life",
    "Opinions, views and emotions run high and passion is their fuel",
    "Pro-Choice activists declare it is a woman’s right to choose what she does with her own body",
    "The biology versus medical definitions proclaim that an embryo is not yet a human life",
    "As conception begins two to three weeks after implantation occurs, a heartbeat is heart",
    "Life is a repeating cycle of endless trials and unexpected changes",
    "No matter how many trials had been experienced, the test in faith never ends",
    "One of life’s many unanswered questions is life after the end of mortality",
    "The gym is a \"stone’s throw from the beach\". I loved it.",
    "I’m \"sitting on the fence\" with this one, you’re both my good friends",
    "Mum, don’t \"freak out!\" I married a guy in Las Vegas.",
    "My doctor \"hit the nail on the head\". He knew exactly what was wrong with me!",
    "The only plausible way humans are able to conjure up an answer is through religion",
    "This story is more like a slice of pie",
    "To make this pie you will need ingredients that aren’t usually in pie",
    "Army life can be very challenging and a life changing experience",
    "It was very challenging and life changing for me",
    "I was raised by my Grandparents they did everything for me so this was a wakeup call for me on life",
    "An independent person was not I, so I had problems with the changes about to come",
    "Army life is constantly demanding and constantly changing without notice",
    "Many people have different perceptions on the value of life",
    "What could make the purpose of life worth living",
    "Or perhaps it is the unsureness of the life after death that may make one cling to their being",
    "At the moment of birth superstitiously, we are given purpose or destiny that we were born to live",
    "Everyone as a young child grows up dreaming of their true purpose in society",
    "As teenagers we get a sense of reality towards the near future of our ideal role to be",
    "Who is allowed to determine how valuable a person’s life is",
    "I passed by \"the skin of my teeth\"",
    "Now he just visits us \"once in a blue moon\"",
    "\"Just hang in there\" and he will call you",
    "I haven’t slept for twenty hours and \"I’m running on fumes\"",
    "The government has been putting a dollar sign value on a person’s life",
    "To quote Julia Alvarez, \"In a world without books, we would not be the same critter\"",
    "The diagnosis of cancer is devastating news to anyone",
    "Picture yourself in a peaceful sleep",
    "Suddenly, you are awake",
    "The crackle of lightening and the swaying of the boat startle you",
    "You get up to see what all the commotion is about",
    "Now you are standing on the deck with the wind knocking you down",
    "The skies open up with the cooling mist from the high waves are gently falling upon you",
    "A piercing alarm and the screaming of people scratches at your ears",
    "Looking back at childhood, children sat down in circles around their teacher to hear stories, fables, and fairytales",
    "These narratives removed children from reality and hid them from the ugliness that is man-kind",
    "Many stories provided direction for the children with dreams for the future",
    "They provided meaning and one of the most important feelings; hope"
  ]
}